"use client";

import { FormEvent, useEffect, useState } from "react";
import { DataChart } from "@/components/DataChart";
import { applyCleaning, askDataset, createChart, createReportJob, createSession, deleteDataset, deleteSavedAnalysis, downloadExport, downloadJobResult, drillDown, getDataset, getInsights, getJob, getProfile, getQuality, getVersions, inspectWorkbook, listDatasets, listSavedAnalyses, previewCleaning, resetDataset, restoreVersion, runSavedAnalysis, saveAnalysis, uploadDataset } from "@/services/api";
import type { AskResponse, ChartResponse, ChartType, CleaningOperation, CleaningPreview, CleaningType, DatasetMetadata, DatasetProfile, DatasetVersion, Insight, Job, QualityIssue, ReportOptions, SavedAnalysis } from "@/types/dataset";

const format = (value: number) => new Intl.NumberFormat().format(value);
const tabs = ["Overview", "Ask Data", "Insights", "Charts", "Data Quality", "Clean", "Versions", "Saved Analyses", "Reports", "Export"] as const;
type Tab = typeof tabs[number];

export default function Home() {
  const [file, setFile] = useState<File | null>(null), [sheets, setSheets] = useState<string[]>([]), [sheet, setSheet] = useState("");
  const [dataset, setDataset] = useState<DatasetMetadata | null>(null), [profile, setProfile] = useState<DatasetProfile | null>(null);
  const [active, setActive] = useState<Tab>("Overview"), [question, setQuestion] = useState(""), [answer, setAnswer] = useState<AskResponse | null>(null);
  const [insights, setInsights] = useState<Insight[]>([]), [quality, setQuality] = useState<QualityIssue[]>([]);
  const [chartQuestion, setChartQuestion] = useState(""), [chartType, setChartType] = useState<ChartType>("bar"), [chart, setChart] = useState<ChartResponse | null>(null);
  const [cleanType, setCleanType] = useState<CleaningType>("trim_whitespace"), [cleanColumn, setCleanColumn] = useState(""), [fillValue, setFillValue] = useState("");
  const [cleanOperation, setCleanOperation] = useState<CleaningOperation | null>(null), [preview, setPreview] = useState<CleaningPreview | null>(null);
  const [versions, setVersions] = useState<DatasetVersion[]>([]);
  const [library, setLibrary] = useState<DatasetMetadata[]>([]), [savedAnalyses, setSavedAnalyses] = useState<SavedAnalysis[]>([]), [sessionId, setSessionId] = useState<string>();
  const [savedName, setSavedName] = useState(""), [job, setJob] = useState<Job | null>(null), [breadcrumb, setBreadcrumb] = useState<string[]>([]), [nextDimension, setNextDimension] = useState("");
  const [reportOptions, setReportOptions] = useState<ReportOptions>({ title: "DataPilot AI Analysis Report", include_profile: true, include_insights: true, include_quality: true, include_charts: true, include_version_history: true, format: "pdf", async_job: true });
  const [reportBusy, setReportBusy] = useState(false), [chartTitle, setChartTitle] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState("");

  useEffect(() => { listDatasets().then(setLibrary).catch(() => undefined); }, []);

  async function chooseFile(selected: File | null) { setFile(selected); setSheets([]); setSheet(""); setError(""); if (selected && /\.xlsx?$/i.test(selected.name)) try { const found = await inspectWorkbook(selected); setSheets(found); setSheet(found[0] ?? ""); } catch (reason) { fail(reason); } }
  function fail(reason: unknown) { setError(reason instanceof Error ? reason.message : "The request failed"); }
  async function refreshSupporting(id: string) { const [foundInsights, foundQuality, foundVersions, foundSaved] = await Promise.all([getInsights(id), getQuality(id), getVersions(id), listSavedAnalyses(id)]); setInsights(foundInsights); setQuality(foundQuality); setVersions(foundVersions.versions); setSavedAnalyses(foundSaved); }
  async function selectDataset(created: DatasetMetadata) { const foundProfile = await getProfile(created.id); setDataset(created); setProfile(foundProfile); setCleanColumn(foundProfile.categorical_columns[0] ?? foundProfile.numeric_columns[0] ?? foundProfile.columns[0]?.name ?? ""); setNextDimension(foundProfile.categorical_columns[1] ?? foundProfile.categorical_columns[0] ?? ""); const session = await createSession(created.id, "Interactive analysis"); setSessionId(session.id); await refreshSupporting(created.id); }
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return; setBusy(true); setError(""); try { const created = await uploadDataset(file, sheet || undefined); await selectDataset(created); setLibrary(await listDatasets()); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function openDataset(id: string) { setBusy(true); try { await selectDataset(await getDataset(id)); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function removeDataset(id: string) { if (!window.confirm("Delete this dataset and all of its versions, sessions, saved analyses, and reports?")) return; try { await deleteDataset(id); setLibrary(await listDatasets()); if (dataset?.id === id) { setDataset(null); setProfile(null); } } catch (reason) { fail(reason); } }
  async function ask(event: FormEvent) { event.preventDefault(); if (!dataset || !question.trim()) return; setBusy(true); setError(""); try { const response = await askDataset(dataset.id, question, sessionId); setAnswer(response); setSessionId(response.metadata?.session_id ?? sessionId); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function chartSubmit(event: FormEvent) { event.preventDefault(); if (!dataset || !chartQuestion.trim()) return; setBusy(true); setError(""); try { setChart(await createChart(dataset.id, chartQuestion, chartType, chartTitle || undefined)); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  function operation(): CleaningOperation { const noColumn = ["remove_duplicates", "remove_missing_rows"].includes(cleanType); return { type: cleanType, ...(noColumn ? {} : { column: cleanColumn }), ...(cleanType === "fill_missing_value" ? { value: fillValue } : {}) }; }
  async function previewClean() { if (!dataset) return; setBusy(true); setError(""); try { const selected = operation(); setCleanOperation(selected); setPreview(await previewCleaning(dataset.id, [selected])); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function confirmClean() { if (!dataset || !cleanOperation) return; setBusy(true); try { const result = await applyCleaning(dataset.id, [cleanOperation]); setProfile(result.profile); setPreview(null); setCleanOperation(null); await refreshSupporting(dataset.id); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function reset() { if (!dataset) return; setBusy(true); try { setProfile(await resetDataset(dataset.id)); await refreshSupporting(dataset.id); setPreview(null); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function restore(version: number) { if (!dataset || !window.confirm(`Restore version ${version} as a new working version?`)) return; setBusy(true); try { const result = await restoreVersion(dataset.id, version); setProfile(result.profile); await refreshSupporting(dataset.id); } catch (reason) { fail(reason); } finally { setBusy(false); } }
  async function buildReport() { if (!dataset) return; setReportBusy(true); setError(""); setJob(null); try { const accepted = await createReportJob(dataset.id, reportOptions); for (let attempt = 0; attempt < 120; attempt += 1) { const current = await getJob(accepted.job_id); setJob(current); if (["completed", "failed", "cancelled"].includes(current.status)) break; await new Promise((resolve) => setTimeout(resolve, 500)); } } catch (reason) { fail(reason); } finally { setReportBusy(false); } }
  async function saveCurrentAnalysis() { if (!dataset || !answer || !savedName.trim()) return; try { await saveAnalysis(dataset.id, savedName, answer.plan, answer.chart_suggestion ? { type: answer.chart_suggestion.type } : undefined); setSavedName(""); setSavedAnalyses(await listSavedAnalyses(dataset.id)); } catch (reason) { fail(reason); } }
  async function rerunSaved(item: SavedAnalysis) { try { const result = await runSavedAnalysis(item.id); setAnswer({ question: item.name, answer: "Saved analysis recalculated against the current dataset version.", plan: result.plan, result: result.result }); setActive("Ask Data"); } catch (reason) { fail(reason); } }
  async function chartDrill(row: Record<string, string | number | null>) { if (!dataset || !chart || !nextDimension || row[chart.x_axis] == null) return; try { const result = await drillDown(dataset.id, chart.plan, chart.x_axis, row[chart.x_axis], nextDimension, breadcrumb); setBreadcrumb(result.breadcrumb); setChart({ ...chart, x_axis: nextDimension, data: result.result, plan: result.plan, title: `${chart.title} · ${result.breadcrumb.join(" › ")}` }); } catch (reason) { fail(reason); } }

  return <main><aside><div className="brand"><span>DP</span><div>DataPilot <b>AI</b></div></div><nav>{["Dashboard", "Upload Data", ...tabs].map((item) => <a className={item === active ? "active" : ""} key={item}>{item}</a>)}</nav><div className="status"><i/> Local AI mode<br/><small>No API key required</small></div></aside>
    <section className="content"><header><div><p className="eyebrow">WORKSPACE</p><h1>{dataset ? dataset.name : "Upload your data"}</h1><p>{dataset ? "Explore, clean, visualize, and export calculated results." : "Turn spreadsheets into clear, calculated answers."}</p></div><div className="avatar">DA</div></header>
    {!dataset && <><div className="upload-card"><div className="upload-copy"><span className="icon">↥</span><h2>Bring your data aboard</h2><p>Upload a CSV or Excel workbook. Your file is normalized to versioned Parquet storage.</p></div><form onSubmit={upload}><label className="dropzone"><input type="file" accept=".csv,.xlsx,.xls" onChange={(event) => chooseFile(event.target.files?.[0] ?? null)}/><b>{file ? file.name : "Choose a file or drop it here"}</b><span>CSV, XLSX or XLS · up to 25 MB</span></label>{sheets.length > 0 && <label className="field">Worksheet<select value={sheet} onChange={(event) => setSheet(event.target.value)}>{sheets.map((name) => <option key={name}>{name}</option>)}</select></label>}<button disabled={!file || busy}>{busy ? "Analyzing…" : "Upload & analyze"}</button></form></div>{library.length > 0 && <article className="panel workspace-panel"><p className="eyebrow">DATASET LIBRARY</p><h2>Continue an analysis</h2><div className="version-list">{library.map((item) => <div key={item.id}><span>v{item.current_version ?? 0}</span><div><h3>{item.name}</h3><p>{item.rows.toLocaleString()} rows · {item.columns} columns · {item.storage_format ?? "parquet"}</p></div><button className="secondary" onClick={() => openDataset(item.id)}>Open</button><button className="danger" onClick={() => removeDataset(item.id)}>Delete</button></div>)}</div></article>}</>}
    {error && <div className="error">{error}<button onClick={() => setError("")}>×</button></div>}
    {dataset && profile && <><div className="metrics"><article><span>Rows</span><strong>{format(profile.row_count)}</strong><small>working records</small></article><article><span>Columns</span><strong>{profile.column_count}</strong><small>{profile.numeric_columns.length} numeric</small></article><article><span>Missing</span><strong>{format(profile.missing_values)}</strong><small>empty cells</small></article><article><span>Duplicates</span><strong>{format(profile.duplicate_rows)}</strong><small>matching rows</small></article></div>
      <div className="tabs">{tabs.map((tab) => <button className={active === tab ? "selected" : ""} onClick={() => setActive(tab)} key={tab}>{tab}</button>)}</div>
      {active === "Overview" && <article className="panel"><div className="panel-title"><div><p className="eyebrow">DATASET PROFILE</p><h2>Columns at a glance</h2></div><button className="secondary" onClick={() => { setDataset(null); setProfile(null); setFile(null); }}>New upload</button></div><div className="table-wrap"><table><thead><tr><th>Column</th><th>Type</th><th>Unique</th><th>Missing</th><th>Summary</th></tr></thead><tbody>{profile.columns.map((column) => <tr key={column.name}><td><b>{column.name}</b></td><td><em className={`pill ${column.category}`}>{column.category}</em></td><td>{format(column.unique_count)}</td><td>{column.missing_percentage}%</td><td>{column.category === "numeric" ? `Σ ${column.sum?.toLocaleString() ?? "—"}` : column.minimum ? `${String(column.minimum).slice(0,10)} → ${String(column.maximum).slice(0,10)}` : "—"}</td></tr>)}</tbody></table></div></article>}
      {active === "Ask Data" && <article className="panel workspace-panel"><p className="eyebrow">ASK YOUR DATA</p><h2>What would you like to know?</h2><p>Plans are interpreted locally; calculations always run against your dataset. This session is saved automatically.</p><form className="action-form" onSubmit={ask}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Try “Show each region's contribution to total sales”"/><button disabled={busy || !question.trim()}>Ask DataPilot</button></form>{answer && <div className="answer"><span>CALCULATED ANSWER</span><h3>{answer.answer}</h3>{answer.explanation && <div className="calculation-trace"><b>Calculated using</b><small>{answer.explanation.metric || "Rows"} → {answer.explanation.aggregation || "Calculation"}{answer.explanation.grouped_by?.length ? ` · Grouped by ${answer.explanation.grouped_by.join(", ")}` : ""}{answer.explanation.filters?.length ? ` · ${answer.explanation.filters.length} filter(s)` : ""}</small></div>}{answer.metadata && <p className="technical-meta">Dataset version {answer.metadata.dataset_version} · {answer.metadata.execution_ms} ms{answer.metadata.provider_fallback ? " · Local fallback used" : ""}{answer.metadata.cached ? " · Cached" : ""}</p>}<details><summary>View analysis plan and result</summary><pre>{JSON.stringify({ plan: answer.plan, result: answer.result }, null, 2)}</pre></details><div className="clean-form"><input value={savedName} onChange={(event) => setSavedName(event.target.value)} placeholder="Saved analysis name"/><button className="secondary" disabled={!savedName.trim()} onClick={saveCurrentAnalysis}>Save analysis</button>{answer.chart_suggestion && <button className="secondary" onClick={() => { setChartQuestion(question); setChartType(answer.chart_suggestion!.type); setActive("Charts"); }}>Create suggested chart</button>}</div></div>}</article>}
      {active === "Insights" && <section><div className="section-heading"><div><p className="eyebrow">AUTOMATIC INSIGHTS</p><h2>Findings calculated from your data</h2></div></div><div className="card-grid">{insights.map((item, index) => <article className={`insight-card ${item.severity}`} key={`${item.title}-${index}`}><span>{item.type.replaceAll("_", " ")}</span><h3>{item.title}</h3><p>{item.description}</p>{item.value !== null && item.value !== undefined && <strong>{typeof item.value === "number" ? item.value.toLocaleString() : item.value}</strong>}</article>)}{!insights.length && <div className="empty-state">No notable insights were detected.</div>}</div></section>}
      {active === "Charts" && <article className="panel workspace-panel"><p className="eyebrow">CHART BUILDER</p><h2>Visualize calculated results</h2><form className="chart-form" onSubmit={chartSubmit}><input value={chartQuestion} onChange={(event) => setChartQuestion(event.target.value)} placeholder="Show sales by region"/><input value={chartTitle} onChange={(event) => setChartTitle(event.target.value)} placeholder="Optional title"/><select value={chartType} onChange={(event) => setChartType(event.target.value as ChartType)}>{["bar","column","line","pie","scatter"].map((type) => <option key={type}>{type}</option>)}</select><button disabled={busy || !chartQuestion.trim()}>Generate chart</button></form>{chart && <><div className="chart-heading"><div><h3>{chart.title}</h3><p>Interpreted: {chart.interpreted_request}</p>{breadcrumb.length > 0 && <p className="technical-meta">{breadcrumb.join(" › ")}</p>}</div><em>{chart.type}</em></div><label className="field">Drill into<select value={nextDimension} onChange={(event) => setNextDimension(event.target.value)}>{profile.categorical_columns.filter((name) => name !== chart.x_axis).map((name) => <option key={name}>{name}</option>)}</select></label><DataChart chart={chart} onPointClick={chartDrill}/><p className="technical-meta">Click a bar to filter by that value and group by the selected next dimension.</p><details><summary>View underlying chart data</summary><pre>{JSON.stringify(chart.data, null, 2)}</pre></details></>}</article>}
      {active === "Data Quality" && <section><p className="eyebrow">DATA QUALITY</p><h2>Issues worth reviewing</h2><div className="quality-list">{quality.map((item, index) => <article className="quality-item" key={`${item.issue_type}-${item.column}-${index}`}><span className={`severity ${item.severity}`}/><div><h3>{item.issue_type.replaceAll("_", " ")}</h3><p>{item.column ? `${item.column} · ` : ""}{item.count.toLocaleString()} affected</p>{item.examples.length > 0 && <code>{item.examples.join(" · ")}</code>}</div></article>)}{!quality.length && <div className="empty-state success">No quality issues detected.</div>}</div></section>}
      {active === "Clean" && <article className="panel workspace-panel"><p className="eyebrow">PREVIEW-FIRST CLEANING</p><h2>Clean the working dataset safely</h2><p>The original upload is preserved and can always be restored.</p><div className="clean-form"><label>Operation<select value={cleanType} onChange={(event) => { setCleanType(event.target.value as CleaningType); setPreview(null); }}>{["trim_whitespace","standardize_lowercase","standardize_uppercase","standardize_titlecase","remove_duplicates","remove_missing_rows","fill_missing_mean","fill_missing_median","fill_missing_value"].map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label>{!["remove_duplicates","remove_missing_rows"].includes(cleanType) && <label>Column<select value={cleanColumn} onChange={(event) => setCleanColumn(event.target.value)}>{profile.columns.map((column) => <option key={column.name}>{column.name}</option>)}</select></label>}{cleanType === "fill_missing_value" && <label>Fill value<input value={fillValue} onChange={(event) => setFillValue(event.target.value)}/></label>}<button onClick={previewClean} disabled={busy}>Preview changes</button><button className="secondary" onClick={reset} disabled={busy}>Reset to original</button></div>{preview && <div className="clean-preview"><h3>Confirm these changes</h3><p><b>{preview.affected_rows.toLocaleString()}</b> rows and <b>{preview.affected_cells.toLocaleString()}</b> cells affected. Result: {preview.resulting_rows.toLocaleString()} rows.</p>{preview.changes.map((change, index) => <div key={index}><strong>{change.operation.type.replaceAll("_", " ")}</strong><small>Before: {change.before_examples.join(" · ") || "—"}<br/>After: {change.after_examples.join(" · ") || "—"}</small></div>)}<button className="danger" onClick={confirmClean} disabled={busy}>Confirm and apply</button><button className="secondary" onClick={() => setPreview(null)}>Cancel</button></div>}</article>}
      {active === "Versions" && <article className="panel workspace-panel"><p className="eyebrow">VERSION HISTORY</p><h2>Immutable dataset checkpoints</h2><p>Every confirmed cleaning or restore creates a new version. Version 0 always remains the original upload.</p><div className="version-list">{versions.slice().reverse().map((version) => <div key={version.version}><span className={version.is_current ? "version-current" : ""}>v{version.version}{version.is_current ? " · current" : ""}</span><div><h3>{version.description}</h3><p>{new Date(version.created_at).toLocaleString()} · {version.affected_rows.toLocaleString()} affected rows</p></div><button className="secondary" disabled={version.is_current || busy} onClick={() => restore(version.version)}>Restore</button></div>)}</div></article>}
      {active === "Saved Analyses" && <article className="panel workspace-panel"><p className="eyebrow">SAVED ANALYSES</p><h2>Reusable query plans</h2><p>Reruns are validated and calculated against the current dataset version.</p><div className="version-list">{savedAnalyses.map((item) => <div key={item.id}><span>QUERY</span><div><h3>{item.name}</h3><p>Updated {new Date(item.updated_at).toLocaleString()}</p></div><button className="secondary" onClick={() => rerunSaved(item)}>Run</button><button className="danger" onClick={async () => { await deleteSavedAnalysis(item.id); setSavedAnalyses(await listSavedAnalyses(dataset.id)); }}>Delete</button></div>)}{!savedAnalyses.length && <div className="empty-state">Save a result from Ask Data to reuse it here.</div>}</div></article>}
      {active === "Reports" && <article className="panel workspace-panel"><p className="eyebrow">ANALYSIS REPORT</p><h2>Generate a persistent report job</h2><div className="report-options"><label>Report title<input value={reportOptions.title} onChange={(event) => setReportOptions({...reportOptions,title:event.target.value})}/></label><label>Format<select value={reportOptions.format} onChange={(event) => setReportOptions({...reportOptions,format:event.target.value as "html" | "pdf"})}><option value="pdf">PDF</option><option value="html">HTML</option></select></label>{(["include_profile","include_insights","include_quality","include_charts","include_version_history"] as const).map((key) => <label className="check" key={key}><input type="checkbox" checked={reportOptions[key]} onChange={(event) => setReportOptions({...reportOptions,[key]:event.target.checked})}/>{key.replace("include_","").replaceAll("_"," ")}</label>)}<button disabled={reportBusy || !reportOptions.title.trim()} onClick={buildReport}>{reportBusy ? `${job?.stage ?? "Queued"} · ${job?.progress ?? 0}%` : "Generate report"}</button>{job?.status === "completed" && <button className="secondary" onClick={() => downloadJobResult(job)}>Download {reportOptions.format.toUpperCase()}</button>}</div>{job && <div className="answer"><span>JOB {job.status.toUpperCase()}</span><h3>{job.stage}</h3><p>{job.progress ?? 0}% complete</p>{job.error_message && <p className="error">{job.error_message}</p>}</div>}</article>}
      {active === "Export" && <article className="panel workspace-panel"><p className="eyebrow">EXPORT</p><h2>Download your data</h2><p>Export the current cleaned version or the untouched original upload.</p><div className="export-grid">{(["current","original"] as const).map((version) => <div key={version}><h3>{version === "current" ? "Current working data" : "Original upload"}</h3><p>{version === "current" ? "Includes confirmed cleaning changes." : "Preserved exactly as initially parsed."}</p><button onClick={() => downloadExport(dataset.id,"csv",version)}>Export CSV</button><button className="secondary" onClick={() => downloadExport(dataset.id,"xlsx",version)}>Export Excel</button></div>)}</div></article>}
    </>}</section></main>;
}
