"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/auth/AuthContext";
import { adminGet, adminRetryJob, adminUpdateFeedback, adminUserAction, FeedbackAttachment, getFeedbackAttachment } from "@/services/api";

type Json=Record<string,unknown>;
type PageResult={items?:Json[];total?:number;limit?:number;offset?:number;metrics?:Json;[key:string]:unknown};
const sections=new Set(["overview","users","workspaces","usage","health","jobs","errors","storage","providers","feedback","support","audit","business","settings"]);
const nav=[
  {label:"Overview",items:[["overview","Overview"]]},
  {label:"Platform",items:[["users","Users"],["workspaces","Workspaces"],["usage","Usage"]]},
  {label:"Operations",items:[["health","Health"],["jobs","Jobs"],["errors","Errors"],["storage","Storage"],["providers","Providers"]]},
  {label:"Support",items:[["feedback","Feedback"],["support","Support Lookup"]]},
  {label:"Security",items:[["audit","Audit Log"]]},
  {label:"Business",items:[["business","Revenue & Costs"]]},
  {label:"",items:[["settings","Settings"]]},
] as const;
const labels:Record<string,string>={overview:"Platform overview",users:"Users",workspaces:"Workspaces",usage:"Platform usage",health:"Health",jobs:"Jobs",errors:"Errors",storage:"Storage",providers:"Providers",feedback:"Feedback",support:"Support lookup",audit:"System-admin audit",business:"Business metrics",settings:"Admin settings"};

function valueText(value:unknown):string{if(value===null||value===undefined)return "—";if(typeof value==="boolean")return value?"Yes":"No";if(typeof value==="number")return value.toLocaleString();if(typeof value==="object")return JSON.stringify(value);const text=String(value);return /^\d{4}-\d\d-\d\dT/.test(text)?new Date(text).toLocaleString():text;}
function MetricGrid({data}:{data:Json}){return <div className="admin-metrics">{Object.entries(data).map(([key,value])=><article key={key}><span>{key.replaceAll("_"," ")}</span><strong>{valueText(value)}</strong></article>)}</div>}
function DataTable({items,onOpen,actions}:{items:Json[];onOpen?:(item:Json)=>void;actions?:(item:Json)=>ReactNode}){if(!items.length)return <div className="admin-empty">No matching records.</div>;const hidden=new Set(["technical_context","details","payload","safe_filename","storage_key","attachments"]);const keys=Array.from(new Set(items.flatMap(item=>Object.keys(item)))).filter(key=>!hidden.has(key)).slice(0,9);return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{keys.map(key=><th key={key} scope="col">{key.replaceAll("_"," ")}</th>)}{actions&&<th scope="col">Actions</th>}</tr></thead><tbody>{items.map((item,index)=><tr key={String(item.id??index)} onClick={()=>onOpen?.(item)} onKeyDown={event=>{if(event.target===event.currentTarget&&onOpen&&(event.key==="Enter"||event.key===" ")){event.preventDefault();onOpen(item);}}} tabIndex={onOpen?0:undefined} aria-label={onOpen?`Open details for ${valueText(item.email??item.name??item.id)}`:undefined} className={onOpen?"clickable":undefined}>{keys.map(key=>{const text=valueText(item[key]);return <td key={key} title={text}><span className={typeof item[key]==="boolean"?`admin-boolean ${item[key]?"yes":"no"}`:undefined}>{text}</span></td>})}{actions&&<td onClick={event=>event.stopPropagation()}>{actions(item)}</td>}</tr>)}</tbody></table></div>}
function AdminAttachment({feedbackId,attachment}:{feedbackId:string;attachment:FeedbackAttachment}){const[url,setUrl]=useState("");useEffect(()=>{let objectUrl="";getFeedbackAttachment(feedbackId,attachment.id).then(blob=>{objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}).catch(()=>undefined);return()=>{if(objectUrl)URL.revokeObjectURL(objectUrl);};},[feedbackId,attachment.id]);if(!url)return <span className="attachment-loading">Loading {attachment.original_filename}…</span>;const image=attachment.content_type.startsWith("image/");return <a className="admin-attachment" href={url} target={image?"_blank":undefined} download={image?undefined:attachment.original_filename}>{image&&<img src={url} alt={`Feedback attachment ${attachment.original_filename}`}/>}<span>{attachment.original_filename}<small>{(attachment.size/1024).toFixed(1)} KB · {image?"Open preview":"Download"}</small></span></a>}
function UsageTrend({items}:{items:Json[]}){const series=[["analysis","Analyses"],["dataset_upload","Uploads"],["report","Reports"]] as const,max=Math.max(1,...items.flatMap(item=>series.map(([key])=>Number(item[key]??0))));if(!items.length)return <div className="admin-empty">No usage events in this range.</div>;return <div className="admin-trend" role="img" aria-label="Daily analyses, uploads, and reports">{items.map(item=><div className="admin-trend-day" key={String(item.date)}><span>{String(item.date)}</span><div>{series.map(([key,label])=><div key={key} title={`${label}: ${Number(item[key]??0).toLocaleString()}`}><i className={key} style={{width:`${Number(item[key]??0)/max*100}%`}}/><small>{label} · {Number(item[key]??0).toLocaleString()}</small></div>)}</div></div>)}</div>}
function StatusCards({data}:{data:Json}){return <div className="admin-status-grid">{Object.entries(data).map(([key,value])=>{const nested=typeof value==="object"&&value!==null&&!Array.isArray(value)?value as Json:null;return <article key={key}><span>{key.replaceAll("_"," ")}</span>{nested?<dl>{Object.entries(nested).map(([name,item])=><div key={name}><dt>{name.replaceAll("_"," ")}</dt><dd>{valueText(item)}</dd></div>)}</dl>:<strong>{valueText(value)}</strong>}</article>})}</div>}

export default function AdminConsole({section:requested}:{section:string}){
  const section=sections.has(requested)?requested:"overview",auth=useAuth();
  const[data,setData]=useState<PageResult>({}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[appliedSearch,setAppliedSearch]=useState(""),[filter,setFilter]=useState(""),[appliedFilter,setAppliedFilter]=useState(""),[days,setDays]=useState(30),[offset,setOffset]=useState(0),[detail,setDetail]=useState<Json|null>(null),[confirm,setConfirm]=useState<{title:string;run:()=>Promise<unknown>}|null>(null),[menu,setMenu]=useState(false);
  const load=useCallback(async()=>{if(!auth.user?.is_system_admin)return;setLoading(true);setError("");setDetail(null);try{if(section==="settings"){setData({});return;}const params:Record<string,string|number|undefined>={limit:25,offset};if(["overview","usage","business"].includes(section))params.days=days;if(["users","workspaces"].includes(section)&&appliedSearch)params.search=appliedSearch;if(section==="jobs"&&appliedFilter)params.status=appliedFilter;if(section==="feedback"&&appliedFilter)params.status=appliedFilter;if(section==="errors"&&appliedFilter)params.error_code=appliedFilter;if(section==="support"){if(appliedSearch.length<2){setData({items:[]});return;}params.q=appliedSearch;}const result=await adminGet<PageResult>(section,params);setData(section==="support"?{...result,items:(result.results as Json[])??[]}:result);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load the admin console.");}finally{setLoading(false);}},[auth.user,section,offset,days,appliedSearch,appliedFilter]);
  useEffect(()=>{setOffset(0);setSearch("");setAppliedSearch("");setFilter("");setAppliedFilter("");setMenu(false);},[section]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setMenu(false);setDetail(null);setConfirm(null);}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
  async function open(item:Json){if(section!=="users"&&section!=="workspaces")return;try{setDetail(await adminGet<Json>(`${section}/${item.id}`));}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load details.");}}
  function submitSearch(event:FormEvent){event.preventDefault();setOffset(0);setAppliedSearch(search.trim());}
  function requestAction(title:string,run:()=>Promise<unknown>){setConfirm({title,run});}
  async function execute(){if(!confirm)return;try{await confirm.run();setConfirm(null);await load();}catch(reason){setConfirm(null);setError(reason instanceof Error?reason.message:"Admin action failed.");}}
  if(auth.loading)return <div className="page-loader">Loading admin console…</div>;
  if(!auth.user?.is_system_admin)return <div className="admin-denied"><h1>Access denied</h1><p>System administrator permission is required. Workspace administrators cannot access platform operations.</p><Link href="/">Return to user app</Link></div>;
  const items=(data.items as Json[])??[];
  return <div className={`admin-shell ${menu?"menu-open":""}`}><button className="admin-menu" aria-label="Toggle admin navigation" aria-expanded={menu} onClick={()=>setMenu(current=>!current)}>☰</button>{menu&&<button className="admin-nav-backdrop" aria-label="Close admin navigation" onClick={()=>setMenu(false)}/>}<aside className="admin-sidebar"><div className="admin-brand"><span>DP</span><div><b>System Admin</b><small>Platform Console</small></div></div><nav aria-label="System administrator navigation">{nav.map(group=><div key={group.label||"settings"}>{group.label&&<p>{group.label}</p>}{group.items.map(([slug,label])=><Link key={slug} className={section===slug?"active":""} aria-current={section===slug?"page":undefined} href={slug==="overview"?"/admin":`/admin/${slug}`} onClick={()=>setMenu(false)}>{label}</Link>)}</div>)}</nav><Link className="open-user-app" href="/">← Open User App</Link></aside><main className="admin-main"><header><div><p className="eyebrow">SYSTEM ADMIN · METADATA ONLY</p><h1>{labels[section]}</h1><p>Platform operations without access to customer dataset rows.</p></div>{["overview","usage","business"].includes(section)&&<label className="admin-range">Range<select value={days} onChange={event=>setDays(Number(event.target.value))}><option value={1}>Today</option><option value={7}>7 days</option><option value={30}>30 days</option></select></label>}</header>{error&&<div className="error" role="alert">{error}</div>}
  {["users","workspaces","support"].includes(section)&&<form className="admin-toolbar" onSubmit={submitSearch}><input aria-label={`Search ${labels[section]}`} value={search} onChange={event=>setSearch(event.target.value)} placeholder={section==="support"?"Email, workspace, dataset ID, or request ID":"Search by name, email, or ID"}/><button>Search</button>{appliedSearch&&<button type="button" className="secondary" onClick={()=>{setSearch("");setAppliedSearch("");setOffset(0);}}>Clear</button>}</form>}
  {["jobs","feedback","errors"].includes(section)&&<form className="admin-toolbar" onSubmit={event=>{event.preventDefault();setOffset(0);setAppliedFilter(filter.trim());}}><label>Filter{section==="jobs"?<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="">All statuses</option>{["queued","running","completed","failed"].map(value=><option key={value}>{value}</option>)}</select>:section==="feedback"?<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="">All statuses</option>{["new","reviewing","planned","resolved"].map(value=><option key={value}>{value}</option>)}</select>:<input value={filter} onChange={event=>setFilter(event.target.value)} placeholder="Error code"/>}</label><button>Apply</button>{appliedFilter&&<button type="button" className="secondary" onClick={()=>{setFilter("");setAppliedFilter("");setOffset(0);}}>Clear</button>}</form>}
  {loading?<div className="admin-loading" role="status">Loading platform metadata…</div>:<AdminSection section={section} data={data} items={items} open={open} requestAction={requestAction}/>} 
  {typeof data.total==="number"&&data.total>0&&<div className="admin-pagination"><span>{offset+1}–{Math.min(offset+25,data.total)} of {data.total}</span><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><button disabled={offset+25>=data.total} onClick={()=>setOffset(offset+25)}>Next</button></div>}
  {detail&&<div className="admin-detail" role="dialog" aria-modal="true" aria-labelledby="detail-title"><button aria-label="Close details" onClick={()=>setDetail(null)}>×</button><h2 id="detail-title">Metadata detail</h2><pre>{JSON.stringify(detail,null,2)}</pre></div>}
  {confirm&&<div className="admin-modal-backdrop" role="presentation"><div className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{confirm.title}</h2><p>This sensitive platform action will be recorded in the system-admin audit log.</p><div><button autoFocus className="secondary" onClick={()=>setConfirm(null)}>Cancel</button><button className="danger" onClick={()=>void execute()}>Confirm action</button></div></div></div>}</main></div>;
}

function AdminSection({section,data,items,open,requestAction}:{section:string;data:PageResult;items:Json[];open:(item:Json)=>void;requestAction:(title:string,run:()=>Promise<unknown>)=>void}){
  if(section==="overview")return <><MetricGrid data={(data.metrics as Json)??{}}/><div className="admin-alerts">{((data.alerts as Json[])??[]).map((alert,index)=><article key={index} className={String(alert.level)}>{valueText(alert.message)}</article>)}</div><section className="admin-card"><h2>Recent platform activity</h2><DataTable items={(data.recent_activity as Json[])??[]}/></section></>;
  if(section==="users")return <>{data.metrics&&<MetricGrid data={data.metrics}/>}<section className="admin-card"><DataTable items={items} onOpen={open} actions={item=><div className="admin-actions"><button className={item.active?"danger":"secondary"} onClick={()=>requestAction(`${item.active?"Deactivate":"Activate"} ${item.email}?`,()=>adminUserAction(String(item.id),item.active?"deactivate":"activate"))}>{item.active?"Deactivate":"Activate"}</button><button className={item.system_admin?"danger":"secondary"} onClick={()=>requestAction(`${item.system_admin?"Revoke":"Grant"} system-admin access?`,()=>adminUserAction(String(item.id),item.system_admin?"revoke_admin":"grant_admin"))}>{item.system_admin?"Revoke admin":"Grant admin"}</button></div>}/></section></>;
  if(section==="workspaces")return <section className="admin-card"><DataTable items={items} onOpen={open}/></section>;
  if(section==="usage")return <><MetricGrid data={(data.totals as Json)??{}}/><section className="admin-card"><h2>Daily operational trend</h2><UsageTrend items={(data.trend as Json[])??[]}/></section><div className="admin-grid"><section className="admin-card"><h2>Most active workspaces</h2><DataTable items={(data.top_workspaces as Json[])??[]}/></section><section className="admin-card"><h2>Most active users</h2><DataTable items={(data.top_users as Json[])??[]}/></section></div></>;
  if(section==="health")return <><div className={`admin-platform-state ${data.platform_status}`}><span>Platform status</span><strong>{valueText(data.platform_status)}</strong><small>Required database and storage checks determine readiness.</small></div><StatusCards data={Object.fromEntries(Object.entries(data).filter(([key])=>key!=="platform_status"))}/></>;
  if(section==="providers")return <StatusCards data={data}/>;
  if(section==="storage")return <><MetricGrid data={{dataset_bytes:data.dataset_bytes,report_bytes:data.report_bytes,feedback_attachment_bytes:data.feedback_attachment_bytes,temporary_bytes:data.temporary_bytes}}/><div className="admin-grid"><section className="admin-card"><h2>Largest workspaces</h2><DataTable items={(data.workspace_breakdown as Json[])??[]}/></section><section className="admin-card"><h2>Largest datasets</h2><DataTable items={(data.largest_datasets as Json[])??[]}/></section></div><p className="admin-privacy-note">Storage backend: <b>{valueText(data.backend)}</b>. Internal storage paths are intentionally hidden.</p></>;
  if(section==="jobs")return <section className="admin-card"><DataTable items={items} actions={item=>item.retryable?<button onClick={()=>requestAction(`Retry job ${item.id}?`,()=>adminRetryJob(String(item.id)))}>Retry</button>:<span>—</span>}/></section>;
  if(section==="feedback")return <section className="admin-feedback-list">{items.length?items.map(item=><article className="admin-card" key={String(item.id)}><div className="feedback-meta"><div><span className={`status-badge ${item.status}`}>{valueText(item.status)}</span> <span className="status-badge">{valueText(item.priority)} priority</span> <span className="status-badge">{valueText(item.category)}</span></div><small>{valueText(item.created_at)}</small></div><h2>{valueText(item.message)}</h2><p>{valueText(item.user_email)} · {valueText(item.workspace_name??item.workspace_id)}</p>{Boolean(item.technical_context)&&<details><summary>Technical context and request reference</summary><pre>{JSON.stringify(item.technical_context,null,2)}</pre></details>}<div className="admin-attachments">{((item.attachments as FeedbackAttachment[])??[]).map(attachment=><AdminAttachment key={attachment.id} feedbackId={String(item.id)} attachment={attachment}/>)}</div><div className="admin-actions"><select aria-label="Feedback status" value={String(item.status)} onChange={event=>requestAction(`Change feedback status to ${event.target.value}?`,()=>adminUpdateFeedback(String(item.id),event.target.value,String(item.priority??"medium")))}>{["new","reviewing","planned","resolved"].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Feedback priority" value={String(item.priority??"medium")} onChange={event=>requestAction(`Change feedback priority to ${event.target.value}?`,()=>adminUpdateFeedback(String(item.id),String(item.status),event.target.value))}>{["low","medium","high"].map(value=><option key={value}>{value}</option>)}</select></div></article>):<div className="admin-empty">No matching feedback.</div>}</section>;
  if(section==="business")return <><MetricGrid data={{beta_users:data.beta_users,external_ai_calls:data.external_ai_calls,storage_bytes:data.storage_bytes}}/><section className="admin-card"><h2>Plan distribution</h2><DataTable items={(data.plan_distribution as Json[])??[]}/></section><section className="admin-unavailable"><h2>Revenue metrics unavailable</h2><p>{valueText(data.revenue_message)}</p></section></>;
  if(section==="settings")return <section className="admin-card"><h2>System administrator management</h2><p>Use the audited local CLI commands to bootstrap or remove system administrators:</p><code>python -m app.cli make-system-admin admin@example.com</code><code>python -m app.cli remove-system-admin admin@example.com</code><p>Workspace Admin manages one workspace. System Admin operates the DataPilot platform.</p></section>;
  if(items.length)return <section className="admin-card"><DataTable items={items}/></section>;
  const entries=Object.entries(data).filter(([key])=>!["items","total","limit","offset"].includes(key));
  return <section className="admin-card"><div className="diagnostic-grid">{entries.map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><b>{valueText(value)}</b></div>)}</div></section>;
}
