"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/auth/AuthContext";
import { CopyLink } from "@/components/CopyLink";
import { cancelWorkspaceDeletion, exportWorkspace, getProviderStatus, getSubscription, getUsage, inviteMember, Invitation, listInvitations, listMembers, Member, ProviderStatus, removeMember, requestAccountDeletion, requestWorkspaceDeletion, resendInvitation, resendVerification, revokeInvitation, startTrial, SubscriptionState, updateMemberRole, updateUser, updateWorkspace, type Usage } from "@/services/api";

export default function SettingsPage() {
  const auth=useAuth(),router=useRouter();
  const[usage,setUsage]=useState<Usage|null>(null),[subscription,setSubscription]=useState<SubscriptionState|null>(null),[provider,setProvider]=useState<ProviderStatus|null>(null),[members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]);
  const[name,setName]=useState(""),[workspaceName,setWorkspaceName]=useState(""),[inviteEmail,setInviteEmail]=useState(""),[inviteRole,setInviteRole]=useState<"admin"|"member">("member"),[externalAi,setExternalAi]=useState(true);
  const[deleteConfirmation,setDeleteConfirmation]=useState(""),[accountPassword,setAccountPassword]=useState("");
  const[message,setMessage]=useState(""),[error,setError]=useState(""),[developmentLink,setDevelopmentLink]=useState<{url:string;label:string}|null>(null),[busyAction,setBusyAction]=useState("");
  const manager=auth.workspace?.role==="owner"||auth.workspace?.role==="admin";
  async function load(){if(!auth.workspace)return;const[foundUsage,foundSubscription,foundProvider,foundMembers]=await Promise.all([getUsage(),getSubscription(auth.workspace.id),getProviderStatus(),listMembers(auth.workspace.id)]);setUsage(foundUsage);setSubscription(foundSubscription);setProvider(foundProvider);setMembers(foundMembers);setExternalAi(foundProvider.external_ai_enabled);setInvitations(manager?await listInvitations(auth.workspace.id):[]);}
  useEffect(()=>{if(!auth.loading&&!auth.user)router.replace("/login");if(auth.user&&auth.workspace){setName(auth.user.display_name);setWorkspaceName(auth.workspace.name);load().catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load settings"));}},[auth.loading,auth.user,auth.workspace?.id,router]);
  function notify(text:string){setMessage(text);setError("");window.setTimeout(()=>setMessage(""),4500);}
  async function save(event:FormEvent){event.preventDefault();if(!auth.workspace)return;setError("");setBusyAction("save");try{await Promise.all([updateUser(name),updateWorkspace(auth.workspace.id,{name:workspaceName,...(manager?{external_ai_enabled:externalAi}:{})})]);await auth.refresh();notify("Settings saved.");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save settings");}finally{setBusyAction("");}}
  async function requestVerification(){setBusyAction("verification");setDevelopmentLink(null);try{const result=await resendVerification();notify(result.message);if(result.development_verification_url)setDevelopmentLink({url:result.development_verification_url,label:"verification link"});}catch(reason){setError(reason instanceof Error?reason.message:"Something went wrong while requesting verification.");}finally{setBusyAction("");}}
  async function invite(event:FormEvent){event.preventDefault();if(!auth.workspace)return;setBusyAction("invite");setDevelopmentLink(null);try{const result=await inviteMember(auth.workspace.id,inviteEmail,inviteRole);setInviteEmail("");await load();if(result.development_invitation_url){setDevelopmentLink({url:result.development_invitation_url,label:"invitation link"});notify("Invitation created successfully. Development email delivery is disabled.");}else notify(`Invitation email accepted by the provider for ${result.email}.`);}catch(reason){setError(reason instanceof Error?reason.message:"Something went wrong while sending the invitation.");}finally{setBusyAction("");}}
  async function resend(item:Invitation){if(!auth.workspace)return;setBusyAction(item.id);setDevelopmentLink(null);try{const result=await resendInvitation(auth.workspace.id,item.id);await load();if(result.development_invitation_url)setDevelopmentLink({url:result.development_invitation_url,label:"invitation link"});notify(result.development_invitation_url?"Invitation renewed. Copy the new development link below.":`Invitation email accepted by the provider for ${result.email}.`);}catch(reason){setError(reason instanceof Error?reason.message:"Something went wrong while resending the invitation.");}finally{setBusyAction("");}}
  async function queueExport(){if(!auth.workspace)return;setBusyAction("export");try{const result=await exportWorkspace(auth.workspace.id);notify(`Workspace export queued. Job ${result.job_id.slice(0,8)} is visible in session history.`);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to queue workspace export.");}finally{setBusyAction("");}}
  async function scheduleDeletion(){if(!auth.workspace||!confirm(`Schedule permanent deletion of ${auth.workspace.name}? The workspace becomes read-only immediately.`))return;setBusyAction("delete-workspace");try{const result=await requestWorkspaceDeletion(auth.workspace.id,deleteConfirmation);setDeleteConfirmation("");await auth.refresh();notify(`Workspace deletion scheduled for ${new Date(result.deletion_scheduled_for).toLocaleString()}.`);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to schedule deletion.");}finally{setBusyAction("");}}
  async function cancelDeletion(){if(!auth.workspace)return;setBusyAction("cancel-deletion");try{await cancelWorkspaceDeletion(auth.workspace.id);await auth.refresh();notify("Workspace deletion cancelled.");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to cancel deletion.");}finally{setBusyAction("");}}
  async function deleteAccount(){if(!accountPassword||!confirm("Request permanent account deletion? You will be signed out."))return;setBusyAction("delete-account");try{await requestAccountDeletion(accountPassword);await auth.logout();router.replace("/login");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to request account deletion.");setBusyAction("");}}
  async function activateTrial(){if(!auth.workspace)return;setBusyAction("trial");try{await startTrial(auth.workspace.id);await load();notify("Your Pro trial is active.");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to start trial.");}finally{setBusyAction("");}}
  if(auth.loading||!auth.user)return <div className="page-loader">Loading settings…</div>;
  return <div className="simple-page settings-page"><header><div><p className="eyebrow">ACCOUNT & WORKSPACE</p><h1>Settings</h1><p>Manage your beta account, collaborators, privacy, and usage.</p></div><div className="account-tools">{auth.user.is_system_admin&&<Link className="button-link" href="/admin">System Admin Console</Link>}<Link className="button-link" href="/">Back to dashboard</Link></div></header>
    {message&&<div className="success-banner" role="status">{message}</div>}{error&&<div className="error" role="alert">{error}</div>}{developmentLink&&<CopyLink url={developmentLink.url} label={developmentLink.label}/>}
    {subscription&&<section className="panel plan-settings-card"><div><p className="eyebrow">CURRENT PLAN · {subscription.plan_source.toUpperCase()}</p><h2>{subscription.effective_plan.name}</h2><p>{subscription.effective_plan.description}</p>{subscription.trial.status==="active"&&<p className="trial-notice">Trial ends in {subscription.trial.days_remaining} days · {new Date(subscription.trial.ends_at!).toLocaleDateString()}</p>}<small>{subscription.data_retention_policy}</small></div><div className="plan-settings-actions">{auth.workspace?.role==="owner"&&subscription.trial.eligible&&<button type="button" disabled={busyAction==="trial"} onClick={activateTrial}>{busyAction==="trial"?"Starting…":"Start Pro trial"}</button>}<Link className="button-link" href="/pricing">View plans</Link></div></section>}
    <section className="panel"><div className="panel-title"><div><p className="eyebrow">EMAIL STATUS</p><h2>{auth.user.email_verified_at?"Verified":"Unverified"}</h2><p>{auth.user.email_verified_at?`Verified ${new Date(auth.user.email_verified_at).toLocaleDateString()}`:"Verification is required for invitations and external AI access."}</p></div>{!auth.user.email_verified_at&&<button type="button" disabled={busyAction==="verification"} onClick={requestVerification}>{busyAction==="verification"?"Requesting…":"Resend verification email"}</button>}</div></section>
    <div className="settings-grid"><form className="panel settings-form" onSubmit={save}><h2>Profile and workspace</h2><label>Display name<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Workspace name<input value={workspaceName} disabled={!manager} onChange={event=>setWorkspaceName(event.target.value)}/></label><label>Workspace slug<input disabled value={auth.workspace?.slug??""}/></label>{manager&&<label className="check"><input type="checkbox" checked={externalAi} onChange={event=>setExternalAi(event.target.checked)}/> Allow configured external AI provider</label>}<button disabled={busyAction==="save"}>{busyAction==="save"?"Saving…":"Save changes"}</button></form>{usage&&<article className="panel"><p className="eyebrow">{usage.plan_code.toUpperCase()} PLAN</p><h2>Current usage</h2>{[["Datasets","datasets"],["Storage","storage_bytes"],["Members","workspace_members"],["Analyses","analyses_per_month"],["External AI","external_ai_calls_per_month"],["Reports","reports_per_month"]].map(([label,key])=>{const item=usage.usage[key];return item?<div className={`usage-row ${item.level}`} key={key}><div><b>{label}</b><span>{key==="storage_bytes"?`${(item.used/1024/1024).toFixed(1)} / ${(item.limit/1024/1024).toFixed(0)} MB`:`${item.used.toLocaleString()} / ${item.limit.toLocaleString()}`}</span></div><progress value={item.used} max={item.limit||1}/>{item.level!=="normal"&&<small>{item.level==="limit"?"Limit reached":item.level==="critical"?"Approaching limit":"Usage notice"} · <Link href="/pricing">View plans</Link></small>}</div>:null})}</article>}</div>
    {provider&&<article className="panel"><p className="eyebrow">AI PRIVACY · {provider.app_version}</p><h2>Provider status: {provider.effective_provider}</h2><p>{provider.privacy_notice}</p>{provider.configured_provider!==provider.effective_provider&&<p className="technical-meta">Configured {provider.configured_provider}; using deterministic Mock because workspace policy or verification restricts external access.</p>}</article>}
    <section className="panel"><h2>Members</h2><div className="version-list">{members.map(member=><div key={member.user_id}><span className={`status-badge ${member.role}`}>{member.role}</span><div><h3>{member.display_name}</h3><p>{member.email} · Joined {new Date(member.joined_at).toLocaleDateString()}</p></div>{manager&&member.role!=="owner"&&<><select aria-label={`Role for ${member.display_name}`} value={member.role} onChange={async event=>{await updateMemberRole(auth.workspace!.id,member.user_id,event.target.value as "admin"|"member");await load();}}><option value="member">member</option><option value="admin">admin</option></select><button type="button" className="danger" onClick={async()=>{if(confirm("Remove this workspace member?")){await removeMember(auth.workspace!.id,member.user_id);await load();}}}>Remove</button></>}</div>)}</div></section>
    {manager&&<section className="panel"><h2>Invitations</h2><form className="report-options" onSubmit={invite}><label>Email<input type="email" required value={inviteEmail} onChange={event=>setInviteEmail(event.target.value)}/></label><label>Role<select value={inviteRole} onChange={event=>setInviteRole(event.target.value as "admin"|"member")}><option value="member">member</option><option value="admin">admin</option></select></label><button disabled={busyAction==="invite"}>{busyAction==="invite"?"Creating…":"Send invitation"}</button></form><div className="version-list">{invitations.map(item=><div key={item.id}><span className={`status-badge ${item.status}`}>{item.status}</span><div><h3>{item.email}</h3><p>{item.role} · {item.status==="pending"?`Expires ${new Date(item.expires_at).toLocaleString()}`:`Created ${new Date(item.created_at).toLocaleDateString()}`}</p></div>{item.status!=="accepted"&&<button type="button" className="secondary" disabled={busyAction===item.id} onClick={()=>resend(item)}>{busyAction===item.id?"Resending…":"Resend"}</button>}{item.status==="pending"&&<button type="button" className="danger" onClick={async()=>{await revokeInvitation(auth.workspace!.id,item.id);await load();notify("Invitation revoked.");}}>Revoke</button>}</div>)}</div></section>}
    <article className="panel"><p className="eyebrow">DATA PORTABILITY & DELETION</p><h2>Workspace lifecycle</h2><p>Exports run in the background and appear in session history. Scheduled deletion makes a workspace read-only immediately and permanently removes its data after the grace period.</p><div className="report-options"><button type="button" className="secondary" disabled={busyAction==="export"} onClick={queueExport}>{busyAction==="export"?"Queueing…":"Export workspace metadata"}</button>{auth.workspace?.role==="owner"&&(auth.workspace.deletion_scheduled_for?<><p className="technical-meta">Deletion scheduled for {new Date(auth.workspace.deletion_scheduled_for).toLocaleString()}.</p><button type="button" disabled={busyAction==="cancel-deletion"} onClick={cancelDeletion}>Cancel deletion</button></>:<><label>Type <strong>{auth.workspace.name}</strong> to confirm<input value={deleteConfirmation} onChange={event=>setDeleteConfirmation(event.target.value)}/></label><button type="button" className="danger" disabled={busyAction==="delete-workspace"||deleteConfirmation!==auth.workspace.name} onClick={scheduleDeletion}>{busyAction==="delete-workspace"?"Scheduling…":"Schedule workspace deletion"}</button></>)}</div><hr/><h3>Delete account</h3><p>First transfer ownership or schedule deletion for every workspace you own. Your password is required.</p><div className="report-options"><label>Current password<input type="password" autoComplete="current-password" value={accountPassword} onChange={event=>setAccountPassword(event.target.value)}/></label><button type="button" className="danger" disabled={!accountPassword||busyAction==="delete-account"} onClick={deleteAccount}>{busyAction==="delete-account"?"Requesting…":"Request account deletion"}</button></div></article>
  </div>;
}
