"use client";

import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/auth/AuthContext";
import { getFeedbackConfig, submitFeedback, uploadFeedbackAttachments } from "@/services/api";

export default function FeedbackPage(){
  const auth=useAuth(),router=useRouter(),fileInput=useRef<HTMLInputElement>(null);
  const[category,setCategory]=useState("general"),[message,setMessage]=useState(""),[technical,setTechnical]=useState(true),[files,setFiles]=useState<File[]>([]);
  const[limits,setLimits]=useState({max_attachments:3,max_attachment_mb:5,accepted_extensions:[".png",".jpg",".jpeg",".webp",".pdf",".txt",".log"]}),[success,setSuccess]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!auth.loading&&!auth.user)router.replace("/login");if(auth.user)getFeedbackConfig().then(setLimits).catch(()=>undefined);},[auth.loading,auth.user,router]);
  function choose(selected:FileList|null){if(!selected)return;const next=[...files,...Array.from(selected)];if(next.length>limits.max_attachments){setError(`You can attach up to ${limits.max_attachments} files.`);return;}const invalid=next.find(file=>file.size>limits.max_attachment_mb*1024*1024||!limits.accepted_extensions.some(extension=>file.name.toLowerCase().endsWith(extension)));if(invalid){setError(`${invalid.name} is unsupported or larger than ${limits.max_attachment_mb} MB.`);return;}setFiles(next);setError("");if(fileInput.current)fileInput.current.value="";}
  async function submit(event:FormEvent){event.preventDefault();setError("");setSuccess("");setBusy(true);let feedbackId="";try{const prior=JSON.parse(sessionStorage.getItem("datapilot_last_error")??"{}");const created=await submitFeedback({category,message,current_page:window.location.pathname,include_technical_context:technical,request_id:prior.request_id,route:prior.route,error_code:prior.error_code,user_agent:navigator.userAgent});feedbackId=created.id;if(files.length)await uploadFeedbackAttachments(created.id,files);setMessage("");setFiles([]);setSuccess("Thanks—your beta feedback and attachments were submitted.");}catch(reason){const detail=reason instanceof Error?reason.message:"Unable to send feedback";setError(feedbackId?`Feedback was saved, but an attachment failed. ${detail}`:detail);}finally{setBusy(false);}}
  if(auth.loading||!auth.user)return <div className="page-loader">Loading feedback…</div>;
  return <div className="simple-page"><header><div><p className="eyebrow">BETA FEEDBACK</p><h1>Send Feedback</h1><p>Report a bug, UI problem, feature request, or confusing result. Dataset contents are never attached automatically.</p></div><Link className="button-link" href="/">Dashboard</Link></header>{success&&<div className="success-banner" role="status">{success}</div>}{error&&<div className="error" role="alert">{error}</div>}<form className="panel settings-form" onSubmit={submit}><label>Category<select value={category} onChange={event=>setCategory(event.target.value)}><option value="bug">Bug</option><option value="feature_request">Feature request</option><option value="confusing_result">Confusing result</option><option value="general">General feedback</option></select></label><label>Message<textarea required minLength={3} value={message} onChange={event=>setMessage(event.target.value)} aria-describedby="feedback-help"/></label><small id="feedback-help">Describe what happened, what you expected, and how we can reproduce it.</small><label>Attach screenshots or files<input ref={fileInput} type="file" multiple accept={limits.accepted_extensions.join(",")} onChange={event=>choose(event.target.files)}/><small>Up to {limits.max_attachments} files, {limits.max_attachment_mb} MB each. PNG, JPG, WebP, PDF, TXT, or LOG.</small></label>{files.length>0&&<div className="attachment-list" aria-label="Selected attachments">{files.map((file,index)=><div key={`${file.name}-${index}`}><span>{file.name}<small>{(file.size/1024).toFixed(1)} KB</small></span><button type="button" className="secondary" aria-label={`Remove ${file.name}`} onClick={()=>setFiles(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button></div>)}</div>}<label className="check"><input type="checkbox" checked={technical} onChange={event=>setTechnical(event.target.checked)}/> Include app version, current page, browser, and recent error reference. No raw dataset values.</label><button disabled={busy}>{busy?"Submitting…":"Submit feedback"}</button></form></div>;
}
